# Generated by Django 5.0.7 on 2024-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30, null=True)),
                ('pro_price', models.IntegerField(null=True)),
                ('pro_quantity', models.IntegerField(null=True)),
                ('pro_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
